#!/usr/bin/env python
import sys
from query import *

cgfn,query = sys.argv[1:]

if not file(cgfn):
    print "can't read the file"
    sys.exit(1)

cg = CG(cgfn)
X = eval(query)
try:
    def gimmepath(p):
        import os
        p = os.path.normpath(p)
        if os.path.isabs(p):
            return p

        cgdir = os.path.dirname(cgfn)
        pdir = os.path.dirname(p)
        pbase = os.path.basename(p)
        path = os.path.normpath(cgdir + os.path.sep + pdir
                                + os.path.sep + pbase)
        path = os.path.abspath(path)
        cwd = os.getcwd()
        if path.startswith(cwd):
            l = len(cwd) + (1 if not cwd.endswith(os.path.sep) else 0)
            path = path[l:]
        return path

    for s in X:
        print "%s:%s: %s" % (gimmepath(s.file), s.line, s.name)
except TypeError:
    print X
